//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DAYCLINIC_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ambulance_tariff
    {
        public int Radif { get; set; }
        public Nullable<byte> Ambulance_Kind { get; set; }
        public Nullable<byte> Path_Kind { get; set; }
        public Nullable<byte> Tariff_kind { get; set; }
        public Nullable<double> EnterPrice { get; set; }
        public Nullable<double> StopPrice { get; set; }
        public Nullable<double> StopTime { get; set; }
        public Nullable<double> KilometerPrice { get; set; }
        public Nullable<double> KilometerStart { get; set; }
        public string Fromdate { get; set; }
        public string Todate { get; set; }
        public Nullable<int> Usercode { get; set; }
        public string InsertDate { get; set; }
        public string Ipadress { get; set; }
        public Nullable<bool> deleted { get; set; }
    }
}
