//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DAYCLINIC_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cash
    {
        public byte Cash_Code { get; set; }
        public string Cash_Name { get; set; }
        public Nullable<double> Stock { get; set; }
        public Nullable<int> usercode { get; set; }
    }
}
