//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DAYCLINIC_SOFTWARE
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ClinicEntities : DbContext
    {
        public ClinicEntities()
            : base("name=ClinicEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<EmployeeInfoTbl> EmployeeInfoTbls { get; set; }
        public DbSet<PersonTbl> PersonTbls { get; set; }
        public DbSet<TblCompany> TblCompanies { get; set; }
        public DbSet<TblEmployeetype> TblEmployeetypes { get; set; }
        public DbSet<TblManagement> TblManagements { get; set; }
        public DbSet<TblRelation> TblRelations { get; set; }
        public DbSet<Clinic> Clinics { get; set; }
    }
}
