//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DAYCLINIC_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comisions_Members
    {
        public int Comisions_MembersCode { get; set; }
        public string Comisions_membersName { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
