//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DAYCLINIC_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comision
    {
        public int Comision_turnid { get; set; }
        public Nullable<System.Guid> Comision_Guid { get; set; }
        public string IDPerson { get; set; }
        public Nullable<int> persno { get; set; }
        public string Personelcode { get; set; }
        public Nullable<int> Fkvdfamily { get; set; }
        public Nullable<byte> PaientType { get; set; }
        public Nullable<byte> PaientStatus { get; set; }
        public Nullable<int> validcenterzone { get; set; }
        public Nullable<int> Joblocations { get; set; }
        public Nullable<byte> Comision_locations_code { get; set; }
        public Nullable<byte> Comision_kindCode { get; set; }
        public string ComisionDate { get; set; }
        public string ComisionResault { get; set; }
        public Nullable<int> Usercode { get; set; }
        public string Insertdate { get; set; }
        public string ipadress { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<byte> Comisions_Request_C_code { get; set; }
    }
}
