//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DAYCLINIC_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public byte department_code { get; set; }
        public string department1 { get; set; }
        public Nullable<bool> kind { get; set; }
        public string ABS { get; set; }
        public Nullable<bool> ViewStatus { get; set; }
    }
}
