//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DAYCLINIC_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department_post
    {
        public int Department_post_Code { get; set; }
        public Nullable<int> UserCode { get; set; }
        public Nullable<byte> DepartmentCode { get; set; }
        public Nullable<int> PostCode { get; set; }
        public string PostDate { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
