//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DAYCLINIC_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctors_contract
    {
        public int Doctors_contract_Code { get; set; }
        public Nullable<int> Doctors_code { get; set; }
        public Nullable<double> Contract_percent { get; set; }
        public Nullable<byte> tariff_kind { get; set; }
    }
}
