//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DAYCLINIC_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctors_industry_list
    {
        public Nullable<int> UserCode { get; set; }
        public Nullable<byte> DepartmentCode { get; set; }
        public Nullable<int> PostCode { get; set; }
        public Nullable<bool> Status { get; set; }
        public int Expr1 { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public string PersianTitle { get; set; }
        public int Department_post_Code { get; set; }
        public string PostDate { get; set; }
        public string Name { get; set; }
        public string absName { get; set; }
        public string EnglishName { get; set; }
        public string title { get; set; }
        public Nullable<bool> sex { get; set; }
        public Nullable<byte> speciality_kind { get; set; }
        public Nullable<byte> Sscientific_Grade { get; set; }
        public Nullable<byte> speciality { get; set; }
        public Nullable<byte> Fellowship { get; set; }
        public Nullable<byte> educations { get; set; }
        public Nullable<int> personalNO { get; set; }
        public string SN { get; set; }
    }
}
