//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DAYCLINIC_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dr_Procedures_Servives
    {
        public int Code { get; set; }
        public Nullable<int> ServicesCode { get; set; }
        public string Desription { get; set; }
        public string ClinicDesc { get; set; }
        public Nullable<int> ClinicCode { get; set; }
        public Nullable<bool> Kind { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> Xmlcode { get; set; }
    }
}
