//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DAYCLINIC_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMR_CL_cause
    {
        public byte CL_cause_code { get; set; }
        public string CL_cause_anme { get; set; }
        public Nullable<bool> deleted { get; set; }
    }
}
