//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DAYCLINIC_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMR_bedroom_number
    {
        public byte bedroom_number { get; set; }
        public string bedroom_Name { get; set; }
        public Nullable<byte> Room_number { get; set; }
    }
}
