//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DAYCLINIC_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMR_Recipe
    {
        public long Turnid { get; set; }
        public string IDPerson { get; set; }
        public Nullable<int> persno { get; set; }
        public string Personelcode { get; set; }
        public Nullable<int> Fkvdfamily { get; set; }
        public string Turndate { get; set; }
        public string Turntime { get; set; }
        public Nullable<byte> turnNo { get; set; }
        public Nullable<int> DoctorsCode { get; set; }
        public Nullable<byte> TurnStatus { get; set; }
        public Nullable<byte> Shiftcode { get; set; }
        public Nullable<byte> PaientType { get; set; }
        public Nullable<byte> PaientStatus { get; set; }
        public Nullable<byte> Usercode { get; set; }
        public string ipadress { get; set; }
        public Nullable<int> validcenterzone { get; set; }
        public Nullable<int> nursing { get; set; }
        public Nullable<byte> PaientType3 { get; set; }
        public Nullable<byte> Bedrid_part { get; set; }
        public Nullable<byte> Room_no { get; set; }
        public Nullable<byte> bed_no { get; set; }
        public Nullable<int> Bedrid_cause { get; set; }
        public string Enter_time { get; set; }
        public string Exit_time { get; set; }
        public Nullable<byte> CL_cause { get; set; }
        public Nullable<byte> Kind { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<byte> PaientType2 { get; set; }
        public Nullable<System.Guid> Guids { get; set; }
        public Nullable<byte> Teriazh_levels { get; set; }
        public Nullable<double> K_P { get; set; }
        public Nullable<double> K_T { get; set; }
        public Nullable<double> K { get; set; }
        public Nullable<int> Sata_id { get; set; }
        public Nullable<double> cash { get; set; }
    }
}
