//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DAYCLINIC_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelingPrice
    {
        public int HotelingPrice_Code { get; set; }
        public Nullable<int> kindRoomCode { get; set; }
        public Nullable<byte> Evaluations { get; set; }
        public Nullable<byte> Tariff_Kind { get; set; }
        public string FromDate { get; set; }
        public string ToDate { get; set; }
        public Nullable<double> Price { get; set; }
    }
}
