//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DAYCLINIC_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Industry_Med_detail
    {
        public int Radif { get; set; }
        public Nullable<long> TurnId { get; set; }
        public string labrecNo { get; set; }
        public Nullable<long> ServicesId { get; set; }
        public Nullable<int> industry_services { get; set; }
        public string TurnDate { get; set; }
    }
}
