//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DAYCLINIC_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Issurance_contract
    {
        public byte Issurance_contract_code { get; set; }
        public string Issurance_Name { get; set; }
        public Nullable<byte> Issurance_Kind { get; set; }
        public Nullable<double> Issurance_Percent { get; set; }
        public string Issurance_FirstDate { get; set; }
        public string Issurance_EndDate { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<byte> Id_Employeetype { get; set; }
    }
}
