//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DAYCLINIC_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Main_Services
    {
        public int Main_Services_code { get; set; }
        public Nullable<byte> Main_group_Code { get; set; }
        public Nullable<int> Secondary_group_code { get; set; }
        public string Attribute { get; set; }
        public Nullable<int> ServicesCode { get; set; }
        public string Name { get; set; }
        public string comment { get; set; }
        public Nullable<double> K_Anesthesia { get; set; }
        public Nullable<double> K_Professional { get; set; }
        public Nullable<double> K_Technical { get; set; }
        public Nullable<double> K_Total { get; set; }
        public string CreationDate { get; set; }
        public string ModificationDate { get; set; }
        public Nullable<double> Version { get; set; }
        public string TerminologyId { get; set; }
        public string group1 { get; set; }
        public string group2 { get; set; }
        public string group33 { get; set; }
        public string group3 { get; set; }
        public string Group4 { get; set; }
        public string Group5 { get; set; }
        public string English_Name { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> Old_Code { get; set; }
        public Nullable<byte> status_view { get; set; }
    }
}
