//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DAYCLINIC_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Main_group_services
    {
        public Main_group_services()
        {
            this.Secondary_Group_Services = new HashSet<Secondary_Group_Services>();
        }
    
        public byte Main_group_Code { get; set; }
        public string Name { get; set; }
        public Nullable<byte> groupcode { get; set; }
    
        public virtual ICollection<Secondary_Group_Services> Secondary_Group_Services { get; set; }
    }
}
