//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DAYCLINIC_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class multisurgerykind_percent
    {
        public int Code { get; set; }
        public Nullable<byte> multisurgerykind { get; set; }
        public Nullable<byte> priority { get; set; }
        public Nullable<double> percents { get; set; }
        public Nullable<byte> Kind { get; set; }
    }
}
