//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DAYCLINIC_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Name
    {
        public byte number { get; set; }
        public string Name1 { get; set; }
        public string vertion { get; set; }
        public Nullable<byte> degree { get; set; }
        public Nullable<byte> tariffkind { get; set; }
        public Nullable<bool> paient_bracelet { get; set; }
    }
}
