//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DAYCLINIC_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class newcode
    {
        public string Attribute { get; set; }
        public string Code { get; set; }
        public string Value { get; set; }
        public string Comment { get; set; }
        public Nullable<double> RelativeValue { get; set; }
        public Nullable<double> AnesthesiaBaseValue { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string ModificationDate { get; set; }
        public Nullable<double> Version { get; set; }
        public bool Deleted { get; set; }
        public string گروه_خدمتی { get; set; }
        public string TerminologyId { get; set; }
        public Nullable<int> kind1 { get; set; }
        public Nullable<int> maincode { get; set; }
    }
}
