//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DAYCLINIC_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class office
    {
        public byte Office_Code { get; set; }
        public Nullable<int> ValidcenterCode { get; set; }
        public string Dayclinic_ipadress { get; set; }
        public string Dentist_ipadress { get; set; }
        public string Clinic_ipadress { get; set; }
        public string descriptions { get; set; }
        public Nullable<System.Guid> IdInvestigationTypeRef { get; set; }
    }
}
