//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DAYCLINIC_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_OrganizationPost
    {
        public System.Guid ID { get; set; }
        public int code { get; set; }
        public Nullable<System.Guid> IDPersonel { get; set; }
        public Nullable<int> CodePersonel { get; set; }
        public string FromDate { get; set; }
        public string ToDate { get; set; }
        public string Management { get; set; }
        public string Company { get; set; }
        public string SubCompany { get; set; }
        public string SubCompany2 { get; set; }
        public Nullable<int> PostNumber { get; set; }
        public Nullable<int> PeronalGrade { get; set; }
        public Nullable<int> OrganizationGrade { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<int> UserCode { get; set; }
        public string InsertDate { get; set; }
    
        public virtual P_Personel P_Personel { get; set; }
    }
}
