//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DAYCLINIC_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_Personel
    {
        public P_Personel()
        {
            this.P_CurrentPost = new HashSet<P_CurrentPost>();
            this.P_Education_Degree = new HashSet<P_Education_Degree>();
            this.P_OrganizationPost = new HashSet<P_OrganizationPost>();
        }
    
        public Nullable<System.Guid> ID { get; set; }
        public int code { get; set; }
        public Nullable<int> PersNO { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public string Faname { get; set; }
        public string SN { get; set; }
        public Nullable<int> IDNumber { get; set; }
        public string BirthDate { get; set; }
        public string Birth_location { get; set; }
        public string export_location { get; set; }
        public string EnterDate { get; set; }
        public string ExitDate { get; set; }
        public Nullable<byte> ReasonExit { get; set; }
        public Nullable<bool> MaritalStatus { get; set; }
        public Nullable<int> child_count { get; set; }
        public Nullable<bool> Sex { get; set; }
        public string soldier_status { get; set; }
        public Nullable<byte> Employment_Status { get; set; }
        public string assurance_number { get; set; }
        public string bank_number { get; set; }
        public Nullable<byte> Status { get; set; }
        public string Area_name { get; set; }
        public Nullable<int> UserCode { get; set; }
        public string InsertDate { get; set; }
        public string Mobile { get; set; }
        public string Comment { get; set; }
        public string IPadress { get; set; }
    
        public virtual ICollection<P_CurrentPost> P_CurrentPost { get; set; }
        public virtual ICollection<P_Education_Degree> P_Education_Degree { get; set; }
        public virtual ICollection<P_OrganizationPost> P_OrganizationPost { get; set; }
    }
}
