//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DAYCLINIC_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaientSurgeryList
    {
        public int Code { get; set; }
        public Nullable<int> PersNo { get; set; }
        public Nullable<int> Fkvdfamily { get; set; }
        public Nullable<byte> Paienttype { get; set; }
        public Nullable<int> SurgeryDoctors { get; set; }
        public string SurgeryDate { get; set; }
        public Nullable<int> anaesthesia { get; set; }
        public Nullable<byte> SurgeryroomNo { get; set; }
        public Nullable<int> Validcenterzone { get; set; }
        public Nullable<int> Joblocations { get; set; }
        public Nullable<byte> Age { get; set; }
        public Nullable<byte> anaesthesiaKind { get; set; }
        public string LenzNo { get; set; }
        public string Illnesshistory { get; set; }
        public string FirstDiagnostic { get; set; }
        public Nullable<int> UserCode { get; set; }
        public string IpAdress { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string Comment { get; set; }
        public Nullable<byte> DocumentStatus { get; set; }
        public string SurgeryNames { get; set; }
        public Nullable<byte> Surgery_partname_code { get; set; }
        public string Phone { get; set; }
        public Nullable<bool> protez { get; set; }
        public string protezkind { get; set; }
        public string IllnesshistoryNames { get; set; }
    }
}
