//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DAYCLINIC_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Physio_DoctorsServices
    {
        public long DoctorsServices_Code { get; set; }
        public Nullable<long> TurnId { get; set; }
        public Nullable<int> ServicesCode { get; set; }
        public Nullable<byte> Treatment_area { get; set; }
        public Nullable<byte> Treatment_area_count { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<System.Guid> Guids { get; set; }
        public Nullable<System.Guid> Guid_recipe { get; set; }
        public Nullable<double> K_P { get; set; }
        public Nullable<double> K_T { get; set; }
        public Nullable<double> K { get; set; }
        public Nullable<double> cash { get; set; }
    }
}
