//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DAYCLINIC_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Physio_Sessions
    {
        public long sessioncode { get; set; }
        public Nullable<long> Turnid { get; set; }
        public Nullable<byte> Session_number { get; set; }
        public string EnterDate { get; set; }
        public string EnterTime { get; set; }
        public string Exittime { get; set; }
        public Nullable<int> usercode { get; set; }
        public Nullable<bool> kind { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<bool> deleted2 { get; set; }
    }
}
