//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DAYCLINIC_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Physio_Reservetion
    {
        public long Turnid { get; set; }
        public Nullable<int> persno { get; set; }
        public Nullable<int> Fkvdfamily { get; set; }
        public string Currentdate { get; set; }
        public string currentTime { get; set; }
        public string Turndate { get; set; }
        public string Turntime { get; set; }
        public Nullable<byte> turnNo { get; set; }
        public Nullable<int> DoctorsCode { get; set; }
        public Nullable<byte> Shiftcode { get; set; }
        public Nullable<byte> PaientType { get; set; }
        public Nullable<byte> PaientStatus { get; set; }
        public Nullable<byte> TurnStatus { get; set; }
        public Nullable<byte> Usercode { get; set; }
        public Nullable<int> Physiotorapist { get; set; }
        public Nullable<bool> deleted { get; set; }
    }
}
