//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DAYCLINIC_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class psychology_Services
    {
        public int Code { get; set; }
        public Nullable<int> ServicesCode { get; set; }
        public Nullable<byte> Kinduse { get; set; }
        public Nullable<int> Xmlcode { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<byte> levels { get; set; }
    }
}
