//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DAYCLINIC_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sata_Status
    {
        public int Sata_code { get; set; }
        public string Fromdate { get; set; }
        public string Todate { get; set; }
        public Nullable<int> ReceptionCode { get; set; }
        public Nullable<byte> Office_Code { get; set; }
        public Nullable<int> Validcentercode { get; set; }
        public Nullable<byte> Sata_departmentcode { get; set; }
        public string Status { get; set; }
        public string Insertdate { get; set; }
        public string inserttime { get; set; }
        public Nullable<int> usercode { get; set; }
        public string ipadress { get; set; }
    }
}
