//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DAYCLINIC_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Secondary_Group_Services
    {
        public int Secondary_group_code { get; set; }
        public Nullable<byte> main_groupCode { get; set; }
        public string Name { get; set; }
    
        public virtual Main_group_services Main_group_services { get; set; }
    }
}
