//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DAYCLINIC_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class SONO_Shifts
    {
        public byte Shiftcode { get; set; }
        public string Shiftname { get; set; }
        public Nullable<System.DateTime> Fromtime { get; set; }
        public Nullable<System.DateTime> totime { get; set; }
        public Nullable<int> XmlShiftCode { get; set; }
        public Nullable<System.TimeSpan> Fromtime1 { get; set; }
        public Nullable<System.TimeSpan> totime1 { get; set; }
        public Nullable<System.Guid> IdShift { get; set; }
    }
}
