//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DAYCLINIC_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreTa_Kala
    {
        public int Code { get; set; }
        public string selection_Code { get; set; }
        public string Barcode { get; set; }
        public string Company_Code { get; set; }
        public string MESC { get; set; }
        public Nullable<int> Generic_Code { get; set; }
        public string Commercial_name { get; set; }
        public string Generic_Name { get; set; }
        public Nullable<int> Group_Code { get; set; }
        public Nullable<bool> Kala_kind { get; set; }
        public string maker_company { get; set; }
        public string locations { get; set; }
        public Nullable<int> Unit_code { get; set; }
        public Nullable<int> stock { get; set; }
        public Nullable<bool> Kala_Use { get; set; }
        public Nullable<int> Min_use { get; set; }
        public Nullable<int> Max_use { get; set; }
        public Nullable<int> Order_Point { get; set; }
        public Nullable<bool> Send_request { get; set; }
        public Nullable<int> UserCode { get; set; }
        public string ipadress { get; set; }
        public string Insert_date { get; set; }
        public string Insert_Time { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<bool> status2 { get; set; }
    }
}
