//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DAYCLINIC_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class StorePh_import
    {
        public int Import_Code { get; set; }
        public Nullable<int> Factor_Number { get; set; }
        public Nullable<int> Identity_Code { get; set; }
        public string Factor_Date { get; set; }
        public string Request_Date { get; set; }
        public Nullable<int> Company_Code { get; set; }
        public Nullable<int> Request_CodeInt { get; set; }
        public Nullable<int> RCP_CodeInt { get; set; }
        public string Request_MarkInt { get; set; }
        public Nullable<int> Countt { get; set; }
        public Nullable<double> sumt { get; set; }
        public Nullable<double> discount { get; set; }
        public Nullable<double> subtraction { get; set; }
        public Nullable<double> addition { get; set; }
        public Nullable<double> Tax { get; set; }
        public Nullable<double> sum_total { get; set; }
        public Nullable<int> UserCode { get; set; }
        public string ipadress { get; set; }
        public string Insert_date { get; set; }
        public string Insert_time { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<bool> deleted { get; set; }
    }
}
