//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DAYCLINIC_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class storePh_export
    {
        public int Export_code { get; set; }
        public Nullable<int> Department_code { get; set; }
        public Nullable<int> Request_usercode { get; set; }
        public string Request_date { get; set; }
        public string Request_Time { get; set; }
        public Nullable<int> Confirmation_Usercode { get; set; }
        public Nullable<int> subscribe_Usercode { get; set; }
        public string Deliver_date { get; set; }
        public string Deliver_Time { get; set; }
        public Nullable<int> devivery_usercode { get; set; }
        public string transferee { get; set; }
        public Nullable<int> UserCode { get; set; }
        public string ipadress { get; set; }
        public string Insert_date { get; set; }
        public string Insert_time { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<bool> deleted { get; set; }
    }
}
