//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DAYCLINIC_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreTa_Unit
    {
        public int Unit_Code { get; set; }
        public string Description_Fa { get; set; }
        public string Description_En { get; set; }
        public string Comment { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<int> UserCode { get; set; }
        public string ipadress { get; set; }
        public string Insert_date { get; set; }
        public string Insert_Time { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> deleted { get; set; }
    }
}
