//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DAYCLINIC_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class StorePh_importDetail
    {
        public int Detail_Code { get; set; }
        public Nullable<int> Import_Code { get; set; }
        public Nullable<int> Kala_code { get; set; }
        public Nullable<int> Group_code { get; set; }
        public Nullable<int> countt { get; set; }
        public Nullable<int> unit { get; set; }
        public Nullable<double> price_single { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> discount { get; set; }
        public Nullable<double> subtraction { get; set; }
        public Nullable<double> addition { get; set; }
        public Nullable<double> Tax { get; set; }
        public Nullable<double> Consumer_price { get; set; }
        public string Expire_date { get; set; }
        public string BatchNo { get; set; }
        public Nullable<int> Export_code { get; set; }
        public Nullable<int> UserCode { get; set; }
        public string ipadress { get; set; }
        public string Insert_date { get; set; }
        public string Insert_time { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<bool> deleted { get; set; }
        public string Batch_No { get; set; }
    }
}
