//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DAYCLINIC_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class StorePh_exportDetail2
    {
        public int Detail_Code { get; set; }
        public Nullable<int> Export_Code { get; set; }
        public Nullable<int> Kala_code { get; set; }
        public Nullable<int> Request_count { get; set; }
        public Nullable<int> Issue_count { get; set; }
        public Nullable<bool> NIS { get; set; }
        public Nullable<int> UserCode { get; set; }
        public string ipadress { get; set; }
        public string Insert_date { get; set; }
        public string Insert_time { get; set; }
        public Nullable<byte> status { get; set; }
        public Nullable<bool> deleted { get; set; }
        public string comment { get; set; }
    }
}
