//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DAYCLINIC_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class StorePh_Company
    {
        public int Company_code { get; set; }
        public string Name { get; set; }
        public string Economic_Code { get; set; }
        public string Number { get; set; }
        public string National_Code { get; set; }
        public string Postal_Code { get; set; }
        public string Saler_Name { get; set; }
        public string Saler_Phone { get; set; }
        public string Distiributer_Name { get; set; }
        public string Distiributer_Phone { get; set; }
        public string Boss_Name { get; set; }
        public string Boss_Phone { get; set; }
        public Nullable<bool> Kind { get; set; }
        public string Phone { get; set; }
        public string Adress { get; set; }
        public Nullable<int> UserCode { get; set; }
        public string ipadress { get; set; }
        public string Insert_date { get; set; }
        public string Insert_Time { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> deleted { get; set; }
    }
}
