//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DAYCLINIC_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurgeryDevices_group
    {
        public byte Devices_groupCode { get; set; }
        public string Devices_group_desc { get; set; }
        public Nullable<byte> Kind { get; set; }
    }
}
