//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DAYCLINIC_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurgeryDevicesPlanDetail
    {
        public int Code { get; set; }
        public Nullable<int> SurgeryDevicesPlanCode { get; set; }
        public Nullable<int> DevicesCode { get; set; }
        public Nullable<double> Countt { get; set; }
        public Nullable<bool> Deleted { get; set; }
    }
}
