//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DAYCLINIC_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Surgery_Bill_detail
    {
        public int Surgery_billCode { get; set; }
        public Nullable<int> SurgeryTurnid { get; set; }
        public string SurgeryDate { get; set; }
        public string SurgeryTime { get; set; }
        public Nullable<int> AccountingUser { get; set; }
        public Nullable<int> SurgeryServiceslist { get; set; }
        public Nullable<double> Cash { get; set; }
        public Nullable<double> Accounting_Control { get; set; }
        public Nullable<double> Insurance1 { get; set; }
        public Nullable<double> Insurance2 { get; set; }
        public Nullable<double> PaientCash { get; set; }
        public Nullable<double> discount { get; set; }
        public string Bill_Desc { get; set; }
        public Nullable<int> countt { get; set; }
    }
}
