//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DAYCLINIC_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurgeryPaientBedroom
    {
        public int Code { get; set; }
        public Nullable<int> PartRoomCode { get; set; }
        public Nullable<int> SurgeryTurnid { get; set; }
        public string FirstDate { get; set; }
        public string EndDate { get; set; }
        public string FirstTime { get; set; }
        public string EndTime { get; set; }
        public Nullable<byte> Kind { get; set; }
        public Nullable<System.DateTime> Firstdatee { get; set; }
        public Nullable<System.DateTime> enddatee { get; set; }
        public Nullable<bool> deleted { get; set; }
    }
}
