//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DAYCLINIC_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurgeryDetail
    {
        public int SurgeryDetailCode { get; set; }
        public Nullable<long> Turnid { get; set; }
        public string Doc_No { get; set; }
        public string SurgeryDate { get; set; }
        public string SurgeryTime { get; set; }
        public string SurgeryPosition { get; set; }
        public Nullable<byte> SurgeryDirection { get; set; }
        public Nullable<int> SurgeryDoctors { get; set; }
        public Nullable<int> SurgeryAssistant1 { get; set; }
        public Nullable<int> SurgeryAssistant2 { get; set; }
        public Nullable<byte> anesthetist_kind { get; set; }
        public Nullable<int> anesthetist_Name { get; set; }
        public Nullable<int> ScrapNurse { get; set; }
        public Nullable<int> CircularNurse { get; set; }
        public Nullable<int> SupervisorNurse { get; set; }
        public string EnterSurgeryroomDate { get; set; }
        public string EnterSurgeryroomTime { get; set; }
        public string SkinCutDate { get; set; }
        public string SkinCutTime { get; set; }
        public string ExitSurgeryroomdate { get; set; }
        public string ExitSurgeryroomTime { get; set; }
        public string anesthetistStartDate { get; set; }
        public string anesthetistStartTime { get; set; }
        public string anesthetistEndDate { get; set; }
        public string anesthetistEndTime { get; set; }
        public string RecoveryStartDate { get; set; }
        public string RecoveryStartTime { get; set; }
        public string RecoveryEndDate { get; set; }
        public string RecoveryEndTime { get; set; }
        public Nullable<int> anesthetistTime { get; set; }
        public Nullable<int> SurgeryTime2 { get; set; }
        public Nullable<int> RecoveryTime { get; set; }
        public Nullable<byte> SurgeryKind { get; set; }
        public Nullable<byte> MultiSurgeryKind { get; set; }
        public Nullable<byte> anesthetistvalue { get; set; }
        public Nullable<byte> Recoveryvalue { get; set; }
        public Nullable<double> Surgery_K { get; set; }
        public Nullable<double> anesthetist_K { get; set; }
        public Nullable<int> SurgeryDoctors2 { get; set; }
        public Nullable<byte> anesthetist_method { get; set; }
        public Nullable<double> anesthetist_balancing_sums { get; set; }
        public Nullable<double> Surgery_balancing_sums { get; set; }
        public string anesthetist_comment { get; set; }
        public string Surgery_Comment { get; set; }
        public Nullable<byte> anesthetist_sums_kind { get; set; }
        public Nullable<byte> surgery_sums_kind { get; set; }
        public Nullable<int> surgerysums { get; set; }
        public Nullable<int> bihoshisums { get; set; }
        public Nullable<int> devicessums { get; set; }
        public Nullable<int> anesthetistcode { get; set; }
        public Nullable<double> surgery_kp { get; set; }
        public Nullable<double> surgery_kt { get; set; }
    }
}
