//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DAYCLINIC_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Surgery_HistoryIll
    {
        public int Surgery_HistoryIllCode { get; set; }
        public string Descriptions { get; set; }
        public string ICDid { get; set; }
        public Nullable<bool> bihoshibalancing { get; set; }
        public Nullable<bool> surgerybalancing { get; set; }
    }
}
