//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DAYCLINIC_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Surgery_ServicesList
    {
        public int Code { get; set; }
        public string ServicesName { get; set; }
        public string Desc_s { get; set; }
        public Nullable<int> ServicersCode { get; set; }
        public Nullable<int> kind { get; set; }
        public Nullable<byte> GroupCode { get; set; }
        public Nullable<bool> ViewStatus { get; set; }
    }
}
