//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DAYCLINIC_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Surgery_ServicesgroupList
    {
        public int Surgery_ServicesGroupCode { get; set; }
        public string Surgery_ServicesGroupDesc { get; set; }
        public Nullable<byte> Kind { get; set; }
    }
}
