//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DAYCLINIC_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurgeryPaientList
    {
        public int SurgeryPaientList_Code { get; set; }
        public Nullable<int> SurgeryRecipeCode { get; set; }
        public Nullable<int> Surgery_Name { get; set; }
        public Nullable<int> UserCode { get; set; }
        public string IpAdress { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<byte> Priority { get; set; }
        public Nullable<double> Percents { get; set; }
        public Nullable<byte> surgeryKind { get; set; }
        public string commissionNumber { get; set; }
        public Nullable<int> SurgeryDoctors { get; set; }
    }
}
