//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DAYCLINIC_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurgeryDevicesPlan
    {
        public int SurgeryDevicesPlanCode { get; set; }
        public Nullable<byte> KindUse { get; set; }
        public Nullable<int> SurgeryNamesCode { get; set; }
        public string Descriptions { get; set; }
        public Nullable<bool> Deleted { get; set; }
    }
}
