//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DAYCLINIC_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Surgery_Balancing
    {
        public int Surgery_Balancing_Code { get; set; }
        public Nullable<int> Balancing_Code { get; set; }
        public string Descriptions { get; set; }
        public Nullable<byte> Kind { get; set; }
        public Nullable<double> zarib { get; set; }
    }
}
