//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DAYCLINIC_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurgeryNamesView
    {
        public int SurgeryNamesCode { get; set; }
        public Nullable<int> SurgeryCode { get; set; }
        public Nullable<int> SurgeryDoctors { get; set; }
        public Nullable<int> Speciality { get; set; }
        public Nullable<int> anesthetist_Name { get; set; }
        public Nullable<byte> Surgery_PartName_Code { get; set; }
        public byte SurgeryRoomCode { get; set; }
        public string Name { get; set; }
        public string Attribute { get; set; }
        public Nullable<double> K_Anesthesia { get; set; }
        public Nullable<double> K_Professional { get; set; }
        public Nullable<double> K_Technical { get; set; }
        public Nullable<double> K_Total { get; set; }
        public string English_Name { get; set; }
    }
}
