//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DAYCLINIC_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurgeryName
    {
        public int SurgeryNamesCode { get; set; }
        public Nullable<int> SurgeryCode { get; set; }
        public Nullable<int> SurgeryDoctors { get; set; }
        public Nullable<int> Speciality { get; set; }
        public Nullable<byte> Sscientific_Gradecode { get; set; }
        public Nullable<int> anesthetist_Name { get; set; }
        public Nullable<byte> Surgery_PartName_Code { get; set; }
        public byte SurgeryRoomCode { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<double> PreCash { get; set; }
    }
}
