//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DAYCLINIC_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurgeryDevicesPaient
    {
        public int DeviceslistCode { get; set; }
        public Nullable<int> DevicesCode { get; set; }
        public Nullable<int> Kind { get; set; }
        public Nullable<double> Count { get; set; }
        public Nullable<long> SurgeryTurnid { get; set; }
        public Nullable<int> TariffCode { get; set; }
    }
}
