//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DAYCLINIC_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurgeryPaientService
    {
        public int Code { get; set; }
        public Nullable<int> Turnid { get; set; }
        public Nullable<int> ServicesCode { get; set; }
        public Nullable<int> ServicesTurnId { get; set; }
        public string ServicesDate { get; set; }
        public Nullable<int> Doctors_code { get; set; }
        public Nullable<byte> Kind { get; set; }
        public string ID { get; set; }
        public Nullable<bool> deleted { get; set; }
    }
}
