//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DAYCLINIC_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Surgery_Descriptions
    {
        public int SurgeryDescriptionsCode { get; set; }
        public Nullable<long> PaientTurnId { get; set; }
        public Nullable<int> SurgeryDefaultanscode { get; set; }
        public string Surgery_Descriptions1 { get; set; }
        public Nullable<bool> Deleted { get; set; }
    }
}
