//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DAYCLINIC_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class surgeryDevicesTariff
    {
        public int TariifCode { get; set; }
        public Nullable<int> DevicesCode { get; set; }
        public Nullable<double> Cash { get; set; }
        public string Firstdate { get; set; }
        public string EndDate { get; set; }
        public Nullable<double> oldcash { get; set; }
    }
}
