//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DAYCLINIC_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tariff_kind
    {
        public byte Tariffkind_code { get; set; }
        public string Tariffkind_name { get; set; }
        public Nullable<int> year { get; set; }
        public string Startdate { get; set; }
        public string Endadte { get; set; }
        public Nullable<int> Tariff { get; set; }
        public Nullable<byte> kind { get; set; }
        public Nullable<byte> Services_kind { get; set; }
        public Nullable<int> Tariff_T { get; set; }
    }
}
