//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DAYCLINIC_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblManagement
    {
        public TblManagement()
        {
            this.EmployeeInfoTbls = new HashSet<EmployeeInfoTbl>();
            this.TblCompanies = new HashSet<TblCompany>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
    
        public virtual ICollection<EmployeeInfoTbl> EmployeeInfoTbls { get; set; }
        public virtual ICollection<TblCompany> TblCompanies { get; set; }
    }
}
