//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DAYCLINIC_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblUsersView
    {
        public int UserCode { get; set; }
        public Nullable<int> personalNO { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public string SN { get; set; }
        public string DoctorNO { get; set; }
        public Nullable<bool> Active { get; set; }
        public string EnglishName { get; set; }
        public string title { get; set; }
        public byte[] Image { get; set; }
        public string PersianTitle { get; set; }
        public Nullable<byte> educations { get; set; }
        public Nullable<byte> speciality_kind { get; set; }
        public Nullable<byte> Sscientific_Grade { get; set; }
        public Nullable<byte> speciality { get; set; }
        public Nullable<byte> Fellowship { get; set; }
        public string StartDate { get; set; }
        public string Enddate { get; set; }
        public Nullable<bool> Status { get; set; }
        public string phone { get; set; }
        public string mobile { get; set; }
        public string Adress { get; set; }
        public Nullable<bool> sex { get; set; }
    }
}
