//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DAYCLINIC_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValidCenter
    {
        public int Pk_ValidCenterZone { get; set; }
        public string ValidCenterZoneDesc { get; set; }
        public bool Deleted { get; set; }
        public string ValidCenterDesc { get; set; }
        public short pk_ValidCenter { get; set; }
    }
}
