//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DAYCLINIC_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_1
    {
        public double Expr1 { get; set; }
        public Nullable<int> SurgeryRecipeCode { get; set; }
        public Nullable<int> Expr2 { get; set; }
        public Nullable<int> ServicesCode { get; set; }
    }
}
