//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DAYCLINIC_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_2
    {
        public string SurgeryDate { get; set; }
        public string fullname { get; set; }
        public int PersNo { get; set; }
        public string NesbatDesc { get; set; }
        public string companyname { get; set; }
        public Nullable<int> age { get; set; }
        public string Name { get; set; }
        public Nullable<int> fk_vdfamily { get; set; }
        public Nullable<int> ServicesCode { get; set; }
        public Nullable<double> K_Total { get; set; }
        public long Turnid { get; set; }
        public Nullable<double> percents { get; set; }
    }
}
